### PR TITLE
Update RunLogger.py

### PR DESCRIPTION
**Pull request by daniellhotka**
RunLogger Changelog

ln 31: added codes to dungeon_map
ln 69: added array of essence_attributes
ln 78: added array of essence_grade
ln 139: added conditional to detect essences in crates
ln 144: added conditional to detect HoH pieces in crates
ln 160: capitalized B in output, for example: Giant's Keep B10 instead of Giant's Keep b10
ln 175: padded output of seconds value, preventing display of incorrect times: 5:8 -> 5:08
ln 197: capitalized output of word Rune
ln 209: fixed spacing to avoid blanks and capitalized output of line headers, for example: Date, Dungeon, Result, etc

Known Issues:

*Missing instance codes for some elemental halls, will be completed by Wednesday
*Works for HoH but not for Secret Dungeons, the API request has a different name
*HoH instance code may be specific to each HoH, may have to adapt code for April HoH, and then 
generalize.
*Does not correctly detect when you open a Secret Dungeon while running elemental halls, have to 
log an instance when this happens to determine the cause (with FullLogger)

### CODE REVIEW

**Comment by nikhgupta** [comment]
It seems that logging mana on HOH is not being done correctly.
Here are some lines from my runs.csv:

`2016-05-13 04:26,Hydeni Ruins Hell - 5,Win,1:25,2806,0,1,Rune,3*,1236,Guard,45.23%,5,Common,HP +100,,,,,`
`﻿2016-05-13 04:27,Hydeni Ruins Hell - 5,Win,0:32,2408,0,0,Rune,4*,2572,Guard,53.07%,5,Magic,HP +160,,ATK +4,,,`
﻿`2016-05-13 15:55,10032 B1,Win,0:37,5737,0,0,"Unknown drop {""mana"": 2151, ""energy"": 0, ""crystal"": 0}",,,,,,,,,,,,`
﻿`2016-05-13 15:57,10032 B1,Win,0:37,5556,1,0,"Unknown drop {""mana"": 2962, ""energy"": 0, ""crystal"": 0}",,,,,,,,,,,,` 
﻿`2016-05-13 15:57,10032 B1,Win,0:34,4970,0,0,"Unknown drop {""mana"": 2086, ""energy"": 0, ""crystal"": 0}",,,,,,,,,,,,`
`﻿2016-05-13 15:58,10032 B1,Win,0:37,2066,0,0,Summoning Pieces Assassin (Fire) x1,,,,,,,,,,,,`

**Comment by fperegrinvs** [comment]
Correct! Seems that whenever B1 fails to drop pieces, it gives you extra mana

**Comment by nikhgupta** [comment]
@lstern, yes, I believe so too. Drop rates are significantly different for such cases.

**Comment by fperegrinvs** [comment]
@porksmash @dANIel1989l  I guess we to add chest mana to dungeon mana

**Comment by daniellhotka** [comment]
I believe they are rolled into the dungeon gains already, when HoH opens on global I can check a log for it. Should be able to add up the mana gained by monsters and the chest and see what it is doing.

**Comment by PeteAndersen** [comment]
Interesting if it is included inside the chest as a reward. I'll check it out in the raw JSON when the HOH opens and update the swarfarm logger if required.

**Comment by PeteAndersen** [comment]
Yep, inside crate is another set of energy, mana, crystal values if you don't get a piece ([example](http://hastebin.com/suxexerize)). I updated this for swarfarm logging server side [here](https://github.com/porksmash/swarfarm_io/commit/f3cdefbce216de258526fc6ffcc51d7ab4ba7139)

**Pull request merged**
