### PR TITLE
Update RunLogger and SummonLogger

### PR DESCRIPTION
**Pull request by daniellhotka**
Updated RunLogger with all the elemental halls

Updated SummonLogger with all types of summons, except Legendary Pieces and Light & Dark Pieces
Changed method of detecting for Social summons, allowing for Crystal summons

### CODE REVIEW

**Comment by fperegrinvs** [comment]
thanks!

**Comment by fperegrinvs** [comment]
You should include your name as co-author of the run-logger plugin

**Comment by daniellhotka** [comment]
No problem! Glad to be of help! Do you mean in the yapsy file?

**Comment by fperegrinvs** [comment]
Yes

**Pull request merged**
