### PR TITLE
Plugin to generate swarfarm data for friends

### PR DESCRIPTION
**Pull request by J-Saas**
You might have some friends unable or incapable of using SWProxy for
whatever reason. This plugin allows you to visit them and generate a
Swarfarm compatible import file. Came as a request from some in the
r/summonerswar IRC channel.

Note that only equipped runes are available to us and not their entire
inventory. Sadly.

### CODE REVIEW

**Comment by fperegrinvs** [comment]
could you update the readme file ? and also include a on/off flag on swproxy.config ?

**Comment by fperegrinvs** [comment]
@porksmash

**Comment by PeteAndersen** [comment]
I just had a swarfarm plugin merged in to the main code [here](https://github.com/kakaroto/SWProxy/commit/ffc164aac61b8b4141a8a9c8dac9702d21848323). It can be modified to generate a file for friends. I'll look at it tonight. Good idea!

**Comment by fperegrinvs** [comment]
not sure if generating the file for friends (without external plugins)
would be acceptable under current SW proxy feature policy

**Comment by fperegrinvs** [comment]
@kakaroto, do you thing that ths feature should be bundled with SW Proxy ?

**Comment by PeteAndersen** [comment]
I have an idea to make this issue moot. There's already a GenerateVisitFriend plugin which produces a json file with all the raw data. I'll adjust the import code on swarfarm to detect this and import it without errors. The structure is slightly different and it's missing all the inventory info but it shouldn't take long.

**Comment by PeteAndersen** [comment]
Ok, I've pushed it to live. You can see the changes in [the last two commits](https://github.com/porksmash/swarfarm_io/commits/master)

**Pull request merged**
